export class ParameterDto {
    parameter0: string;
    parameter1 : string;
    parameter2 : string;
    parameter3 : string;
    parameter4 : string;
    parameter5 : string;
    parameter6 : string;
    parameter7 : string;
    parameter8 : string;
    parameter9 : string;
    parameter10 : string;
    parameter11 : string;
    parameter12 : string;
    parameter13 : string;
    parameter14 : string;
    parameter15 : string;
    parameter16 : string;
    parameter17 : string;
    parameter18 : string;
    parameter19 : string;
    parameter20 : string;
    parameter21 : string;
    parameter22 : string;
    parameter23 : string;
    parameter24 : string;
    parameter25 : string;
    parameter26 : string;
    parameter27 : string;
    parameter28 : string;
    parameter29 : string;
    parameter30 : string;
    parameter31 : string;
    parameter32 : string;
    parameter33 : string;
    parameter34 : string;
    parameter35 : string;
    parameter36 : string;
    parameter37 : string;
    parameter38 : string;
    parameter39 : string;
    parameter40 : string;
    parameter41 : string;
    parameter42 : string;
    parameter43 : string;
    parameter44 : string;
    parameter45 : string;
    parameter46 : string;
    list :string[]=[];
    getParameterList() : string[]{
        this.list.push(this.parameter0);
        this.list.push(this.parameter1);
        this.list.push(this.parameter2);
        this.list.push(this.parameter3);
        this.list.push(this.parameter4);
        this.list.push(this.parameter5);
        this.list.push(this.parameter6);
        this.list.push(this.parameter7);
        this.list.push(this.parameter8);
        this.list.push(this.parameter9);
        this.list.push(this.parameter10);
        this.list.push(this.parameter11);
        this.list.push(this.parameter12);
        this.list.push(this.parameter13);
        this.list.push(this.parameter14);
        this.list.push(this.parameter15);
        this.list.push(this.parameter16);
        this.list.push(this.parameter17);
        this.list.push(this.parameter18);
        this.list.push(this.parameter19);
        this.list.push(this.parameter20);
        this.list.push(this.parameter21);
        // this.list.push(this.parameter20);
        // this.list.push(this.parameter21);
        this.list.push(this.parameter22);
        this.list.push(this.parameter23);
        this.list.push(this.parameter24);
        this.list.push(this.parameter25);
        this.list.push(this.parameter26);
        this.list.push(this.parameter27);
        this.list.push(this.parameter28);
        this.list.push(this.parameter29);
        // this.list.push(this.parameter27);
        this.list.push(this.parameter30);
        this.list.push(this.parameter31);
        this.list.push(this.parameter32);
        this.list.push(this.parameter33);
        this.list.push(this.parameter34);
        this.list.push(this.parameter35);
        this.list.push(this.parameter36);
        this.list.push(this.parameter37);
        this.list.push(this.parameter38);
        this.list.push(this.parameter39);
        this.list.push(this.parameter40);
        this.list.push(this.parameter41);
        this.list.push(this.parameter42);
        this.list.push(this.parameter43);
        this.list.push(this.parameter44);
        this.list.push(this.parameter45);
        this.list.push(this.parameter46);
        return this.list;
    }

}